-- Recreate consult_complete_view with SECURITY INVOKER to respect RLS of underlying tables
DROP VIEW IF EXISTS public.consult_complete_view;

CREATE VIEW public.consult_complete_view
WITH (security_invoker = true)
AS
SELECT 
    ch.id,
    ch.consult_id,
    ch.clinic_id,
    ch.patient_id,
    ch.owner_id,
    ch.vet_user_id,
    ch.snapshot_type,
    ch.version_number,
    ch.created_at,
    ch.created_by,
    ch.patient_name,
    ch.patient_species,
    ch.patient_breed,
    ch.patient_weight_kg,
    ch.patient_age,
    ch.owner_name,
    ch.owner_email,
    ch.owner_phone,
    ch.vet_name,
    ch.vet_email,
    ch.transcription_complete,
    ch.transcription_method,
    ch.audio_duration_seconds,
    ch.soap_s,
    ch.soap_o,
    ch.soap_a,
    ch.soap_p,
    ch.wellness_data,
    ch.procedure_data,
    ch.vitals,
    ch.case_notes_json,
    ch.reason_for_visit,
    ch.status,
    ch.device_fingerprint,
    ch.ip_address,
    ch.user_agent,
    ch.user_email,
    ch.user_name,
    ch.device_name,
    ch.wellness_patient_info,
    ch.wellness_vitals_weight,
    ch.wellness_physical_exam,
    ch.wellness_assessment,
    ch.wellness_vaccines,
    ch.wellness_preventive_care,
    ch.wellness_diet_nutrition,
    ch.wellness_owner_discussion,
    ch.wellness_recommendations,
    ch.wellness_client_education,
    ch.procedure_summary,
    ch.procedure_pre_assessment,
    ch.procedure_anesthetic_protocol,
    ch.procedure_details,
    ch.procedure_medications,
    ch.procedure_post_status,
    ch.procedure_follow_up,
    ch.procedure_client_comm,
    ch.procedure_email_to_client,
    ch.case_notes,
    ch.discharge_summary,
    ch.client_education,
    ch.pdf_export_content,
    ch.pdf_export_type,
    ch.pdf_exported_at,
    c.finalized_at,
    c.finalized_by,
    c.version AS current_version
FROM consult_history ch
LEFT JOIN consults c ON ch.consult_id = c.id;