import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';

import { Download, Copy, Pill, AlertTriangle, Clock, Thermometer, Trash2, HelpCircle } from 'lucide-react';

// Helper to render text that may contain bullet points
const FormattedText = ({ text }: { text: string | undefined }) => {
  if (!text) return <span className="text-muted-foreground">Not available</span>;
  
  const lines = text.split('\n').filter(line => line.trim());
  const hasBullets = lines.some(line => {
    const trimmed = line.trim();
    return trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*');
  });
  
  if (hasBullets) {
    return (
      <ul className="list-none space-y-1 mt-1">
        {lines.map((line, idx) => {
          const trimmed = line.trim();
          const isBullet = trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*');
          const content = isBullet ? trimmed.replace(/^[•\-\*]\s*/, '') : trimmed;
          
          return isBullet ? (
            <li key={idx} className="flex items-start gap-2">
              <span className="text-primary mt-0.5">•</span>
              <span>{content}</span>
            </li>
          ) : (
            <p key={idx}>{content}</p>
          );
        })}
      </ul>
    );
  }
  
  return <span>{text}</span>;
};
import { toast } from 'sonner';
import { copyToClipboard, isIOS } from '@/utils/clipboard';
import { downloadMedicationPDF, type MedicationProfile } from '@/utils/medicationPdfGenerator';
import type { ClinicInfo } from '@/utils/pdfExport';

interface MedicationProfileDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  drugName: string | null;
  profile: MedicationProfile | null;
  isLoading: boolean;
  clinic: ClinicInfo | null;
  patient: { name: string; species?: string; breed?: string | null } | null;
  onCopyFallback: (text: string) => void;
}

export function MedicationProfileDialog({
  open,
  onOpenChange,
  drugName,
  profile,
  isLoading,
  clinic,
  patient,
  onCopyFallback
}: MedicationProfileDialogProps) {
  
  const handleDownloadPDF = () => {
    if (!profile) return;
    downloadMedicationPDF(profile, clinic, patient);
    toast.success('PDF downloaded successfully');
  };
  
  const handleCopyAll = async () => {
    if (!profile) return;
    
    const text = `MEDICATION PROFILE: ${profile.drugName}
${profile.brandNames ? `Brand Names: ${profile.brandNames}\n` : ''}
DESCRIPTION
${profile.description}

USES
${profile.uses}

DURATION OF THERAPY
${profile.durationOfTherapy}

DURATION OF DRUG EFFECTS
${profile.durationOfEffects}

COMMON SIDE EFFECTS
${profile.commonSideEffects}

SEVERE SIDE EFFECTS
${profile.severeSideEffects}
${(profile as any).animalWarnings ? `\nWARNINGS FOR ANIMALS\n${(profile as any).animalWarnings}` : ''}

STORAGE DIRECTIONS
${profile.storageDirections}

DISPOSAL
${profile.disposal}

MISSED DOSE PROTOCOL
${profile.missedDoseProtocol}

OVERDOSE
${profile.overdose}

---
Generated by whiskr.ai`;

    if (isIOS()) {
      onCopyFallback(text);
      return;
    }
    
    const success = await copyToClipboard(text);
    if (success) {
      toast.success('Medication profile copied to clipboard');
    } else {
      onCopyFallback(text);
    }
  };
  
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-hidden p-0">
        <DialogHeader className="p-6 pb-4 border-b">
          <DialogTitle className="flex items-center gap-2">
            <Pill className="h-5 w-5 text-primary" />
            <span>Medication Profile: {drugName}</span>
          </DialogTitle>
        </DialogHeader>

        <div className="max-h-[calc(90vh-200px)] overflow-auto px-6 py-4">
          {isLoading ? (
            <div className="space-y-4 py-4">
              <Skeleton className="h-6 w-3/4" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-6 w-1/2 mt-4" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-3/4" />
              <Skeleton className="h-6 w-1/2 mt-4" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-full" />
            </div>
          ) : profile ? (
            <div className="space-y-6 py-4">
              {/* Medication Information */}
              <section>
                <h3 className="text-lg font-semibold text-primary mb-3 flex items-center gap-2">
                  <Pill className="h-4 w-4" />
                  Medication Information
                </h3>
                <div className="space-y-2 pl-4">
                  <div>
                    <span className="font-medium">Drug Name: </span>
                    <span>{profile.drugName}</span>
                    {profile.brandNames && (
                      <Badge variant="secondary" className="ml-2 text-xs">
                        {profile.brandNames}
                      </Badge>
                    )}
                  </div>
                  <div>
                    <span className="font-medium">Description/Type: </span>
                    <div className="text-muted-foreground"><FormattedText text={profile.description} /></div>
                  </div>
                </div>
              </section>
              
              {/* Uses & Duration */}
              <section>
                <h3 className="text-lg font-semibold text-primary mb-3 flex items-center gap-2">
                  <Clock className="h-4 w-4" />
                  Uses & Duration
                </h3>
                <div className="space-y-2 pl-4">
                  <div>
                    <span className="font-medium">Uses: </span>
                    <div className="text-muted-foreground"><FormattedText text={profile.uses} /></div>
                  </div>
                  <div>
                    <span className="font-medium">Duration of Therapy: </span>
                    <div className="text-muted-foreground"><FormattedText text={profile.durationOfTherapy} /></div>
                  </div>
                  <div>
                    <span className="font-medium">Duration of Drug Effects: </span>
                    <div className="text-muted-foreground"><FormattedText text={profile.durationOfEffects} /></div>
                  </div>
                </div>
              </section>
              
              {/* Safety & Side Effects */}
              <section>
                <h3 className="text-lg font-semibold text-primary mb-3 flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4" />
                  Safety & Side Effects
                </h3>
                <div className="space-y-2 pl-4">
                  <div>
                    <span className="font-medium">Common Side Effects: </span>
                    <div className="text-muted-foreground"><FormattedText text={profile.commonSideEffects} /></div>
                  </div>
                  <div className="bg-destructive/10 rounded p-2 border border-destructive/20">
                    <span className="font-medium text-destructive">Severe Side Effects: </span>
                    <div className="text-muted-foreground"><FormattedText text={profile.severeSideEffects} /></div>
                  </div>
                  {(profile as any).animalWarnings && (
                    <div className="bg-orange-50 dark:bg-orange-900/20 rounded p-2 border border-orange-200 dark:border-orange-800">
                      <span className="font-medium text-orange-700 dark:text-orange-400">Warnings for Animals: </span>
                      <div className="text-muted-foreground"><FormattedText text={(profile as any).animalWarnings} /></div>
                    </div>
                  )}
                </div>
              </section>
              
              {/* Storage & Disposal */}
              <section>
                <h3 className="text-lg font-semibold text-primary mb-3 flex items-center gap-2">
                  <Thermometer className="h-4 w-4" />
                  Storage & Disposal
                </h3>
                <div className="space-y-2 pl-4">
                  <div>
                    <span className="font-medium">Storage Directions: </span>
                    <div className="text-muted-foreground"><FormattedText text={profile.storageDirections} /></div>
                  </div>
                  <div className="flex items-start gap-2">
                    <Trash2 className="h-4 w-4 mt-0.5 text-muted-foreground" />
                    <div>
                      <span className="font-medium">Disposal: </span>
                      <div className="text-muted-foreground"><FormattedText text={profile.disposal} /></div>
                    </div>
                  </div>
                </div>
              </section>
              
              {/* Missed Dose Protocol */}
              <section>
                <h3 className="text-lg font-semibold text-primary mb-3 flex items-center gap-2">
                  <HelpCircle className="h-4 w-4" />
                  Missed Dose Protocol
                </h3>
                <div className="pl-4 bg-muted/50 rounded p-3">
                  <div className="text-muted-foreground"><FormattedText text={profile.missedDoseProtocol} /></div>
                </div>
              </section>
              
              {/* Overdose */}
              <section>
                <h3 className="text-lg font-semibold text-destructive mb-3 flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4" />
                  Overdose
                </h3>
                <div className="pl-4 bg-destructive/10 rounded p-3 border border-destructive/20">
                  <div className="text-muted-foreground"><FormattedText text={profile.overdose} /></div>
                </div>
              </section>
              
              {/* Disclaimer */}
              <div className="bg-muted/50 rounded p-3 border border-border">
                <p className="text-xs text-muted-foreground italic text-center">
                  <span className="font-semibold not-italic">Disclaimer: </span>
                  This summary is a helpful overview, not a complete medical resource. For full safety details and a treatment plan tailored to your pet, please consult directly with your veterinary healthcare provider.
                </p>
              </div>
            </div>
          ) : (
            <div className="py-8 text-center text-muted-foreground">
              No profile data available
            </div>
          )}
        </div>
        
        {/* Action buttons */}
        {profile && !isLoading && (
          <div className="flex gap-2 p-6 pt-4 border-t flex-shrink-0">
            <Button onClick={handleDownloadPDF} className="flex-1 gap-2">
              <Download className="h-4 w-4" />
              Download PDF
            </Button>
            <Button onClick={handleCopyAll} variant="outline" className="flex-1 gap-2">
              <Copy className="h-4 w-4" />
              Copy All
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
