import jsPDF from "jspdf";
import { format } from "date-fns";
import type { ClinicInfo } from "./pdfExport";

// Brand colors matching the PDF template
const SECTION_BG = { r: 245, g: 245, b: 245 }; // Light gray
const SECTION_TEXT = { r: 32, g: 96, b: 223 }; // Blue text for headings
const BODY_TEXT = { r: 31, g: 41, b: 55 };
const MUTED_TEXT = { r: 107, g: 114, b: 128 };

export interface PatientInfoEdu {
  name: string;
  species?: string;
  breed?: string | null;
}

/**
 * Draw a simple bold title header
 */
function drawHeader(doc: jsPDF, title: string, patientName: string, pageWidth: number): number {
  const margin = 15;

  // Simple bold title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(BODY_TEXT.r, BODY_TEXT.g, BODY_TEXT.b);
  doc.text(title, pageWidth / 2, 25, { align: "center" });

  // Patient info
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(MUTED_TEXT.r, MUTED_TEXT.g, MUTED_TEXT.b);
  doc.text(`For: ${patientName}`, pageWidth / 2, 35, { align: "center" });

  return 50; // Return y position after header
}

/**
 * Draw content with word wrapping and page breaks
 */
function drawContent(
  doc: jsPDF,
  content: string,
  startY: number,
  margin: number,
  contentWidth: number,
  pageHeight: number
): number {
  let yPos = startY;

  const lines = content.split("\n");
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(BODY_TEXT.r, BODY_TEXT.g, BODY_TEXT.b);

  for (const line of lines) {
    const trimmedLine = line.trim();
    
    // Check for section headers (all caps lines)
    const isSectionHeader = /^(?:\d+\.\s*)?[A-Z][A-Z\s?]+$/.test(trimmedLine) && trimmedLine.length > 3;
    
    if (isSectionHeader) {
      // Add some space before section headers
      yPos += 8;
      
      // Check for page break
      if (yPos > pageHeight - 30) {
        doc.addPage();
        yPos = 20;
      }
      
      // Draw section header with background
      const headerHeight = 10;
      doc.setFillColor(SECTION_BG.r, SECTION_BG.g, SECTION_BG.b);
      doc.roundedRect(margin, yPos - 6, contentWidth, headerHeight, 2, 2, "F");
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(SECTION_TEXT.r, SECTION_TEXT.g, SECTION_TEXT.b);
      doc.text(trimmedLine, margin + 4, yPos);
      
      yPos += 12;
      
      // Reset to normal text
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(BODY_TEXT.r, BODY_TEXT.g, BODY_TEXT.b);
      continue;
    }
    
    // Check if this is a bullet point
    const isBullet = trimmedLine.startsWith("•") || trimmedLine.startsWith("-") || trimmedLine.startsWith("*");
    
    if (isBullet) {
      // Check for page break
      if (yPos > pageHeight - 20) {
        doc.addPage();
        yPos = 20;
      }
      
      // Remove bullet character and trim
      const bulletText = trimmedLine.replace(/^[•\-\*]\s*/, "");
      const bulletIndent = margin + 8;
      const bulletTextWidth = contentWidth - 18;

      // Draw bullet character
      doc.text("•", margin + 2, yPos);

      // Wrap and draw bullet text
      const wrappedLines = doc.splitTextToSize(bulletText, bulletTextWidth);
      for (let i = 0; i < wrappedLines.length; i++) {
        if (yPos > pageHeight - 20) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(wrappedLines[i], bulletIndent, yPos);
        yPos += 6;
      }
    } else if (trimmedLine) {
      // Regular text - wrap and draw
      const wrappedLines = doc.splitTextToSize(trimmedLine, contentWidth);
      for (const wrappedLine of wrappedLines) {
        if (yPos > pageHeight - 20) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(wrappedLine, margin, yPos);
        yPos += 6;
      }
    } else {
      // Empty line
      yPos += 4;
    }
  }

  return yPos;
}

/**
 * Draw footer on each page
 */
function addFooters(doc: jsPDF, clinic: ClinicInfo | null, pageWidth: number, pageHeight: number, margin: number) {
  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const footerY = pageHeight - 10;

    // Footer line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);

    // Left: Branding
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(MUTED_TEXT.r, MUTED_TEXT.g, MUTED_TEXT.b);
    doc.text("Generated by whiskr.ai", margin, footerY);

    // Center: Clinic name or date
    if (clinic?.name) {
      doc.text(clinic.name, pageWidth / 2, footerY, { align: "center" });
    } else {
      doc.text(format(new Date(), "MMM d, yyyy"), pageWidth / 2, footerY, { align: "center" });
    }

    // Right: Page number
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, footerY, { align: "right" });
  }
}

/**
 * Generate a Client Education PDF
 */
export function generateClientEducationPDF(
  content: string,
  patient: PatientInfoEdu | null,
  clinic: ClinicInfo | null
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;

  // Draw header
  const patientName = patient?.name || "Your Pet";
  let yPos = drawHeader(doc, "Client Education", patientName, pageWidth);

  // Draw content
  yPos = drawContent(doc, content, yPos, margin, contentWidth, pageHeight);

  // Add footers
  addFooters(doc, clinic, pageWidth, pageHeight, margin);

  return doc;
}

/**
 * Generate and download the client education PDF
 */
export function downloadClientEducationPDF(
  content: string,
  patient: PatientInfoEdu | null,
  clinic: ClinicInfo | null
): void {
  const doc = generateClientEducationPDF(content, patient, clinic);
  const patientName = patient?.name?.replace(/[^a-zA-Z0-9]/g, "_") || "Patient";
  const fileName = `${patientName}_Client_Education.pdf`;
  doc.save(fileName);
}
