// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifwieaefmubornheisld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlmd2llYWVmbXVib3JuaGVpc2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyOTM4NzQsImV4cCI6MjA4NDg2OTg3NH0.BaiKFmzviWYu5Vp2YYUSzC2aj3X-7EDgmOGqKfb-Las";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});